apiVersion: v1
kind: Namespace
metadata:
  name: teltech

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees
  namespace: teltech
spec:
  selector:
    matchLabels:
      app: employees
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: employees
          image: xxx
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - name: c-port
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: employees-service
  namespace: teltech
spec:
  type: NodePort
  selector:
    app: employees
  ports:
    - name: s-port
      port: 80
      targetPort: c-port